---

- name: Install input-remapper
  tags: ["input-remapper", "desktop"]
  ignore_errors: "{{ ansible_check_mode }}"
  block:

    - name: Install dependencies
      ansible.builtin.pip:
        name: "{{ item }}"
        state: present
      loop:
        - evdev
        - pydantic
        - dasbus
        - PyGObject

    - name: Clone input-remapper
      ansible.builtin.git:
        repo: https://github.com/sezanzeb/input-remapper.git
        dest: /tmp/input-remapper
        clone: true
        update: true
        version: main

    - name: Install input-remapper service
      ansible.builtin.command:
        cmd: python3 -m install --root /
        chdir: /tmp/input-remapper
        creates: /etc/systemd/system/input-remapper.service
      notify: Daemon reload

    - name: Enable input-remapper service
      ansible.builtin.systemd:
        name: input-remapper
        enabled: true
        state: started
