---
# tasks file for b08x.devworkstation.desktop

- name: Display the value of desktop_my_variable
  ansible.builtin.debug:
    msg: "The value of desktop_my_variable is {{ desktop_my_variable }}"

- name: Include GNOME desktop installation tasks
  ansible.builtin.include_tasks: gnome.yml
  when: desktop_environment == 'gnome'
  tags: ["gnome"]

- name: Ensure Flathub remote repository is present
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: system
    state: present
  tags: ["flathub"]

- name: Include VS Code installation tasks
  ansible.builtin.include_tasks: vscode.yml

- name: Include input-remapper tasks
  ansible.builtin.include_tasks: input-remapper.yml
  tags: ["input-remapper"]

- name: Install Flatpak applications
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    method: system
    remote: flathub
  loop:
    - com.google.Chrome
    - io.github.vikdevelop.SaveDesktop
    - com.mattjakeman.ExtensionManager
    - com.ranfdev.DistroShelf
    - io.github.input_leap.input-leap
    - io.podman_desktop.PodmanDesktop
    - page.tesk.Refine
    - org.gnome.DejaDup
    - io.github.flattool.Ignition
    - md.obsidian.Obsidian
  tags: ["flatpaks"]

- name: Install Additional Flatpak applications
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    method: system
    remote: flathub
  loop:
    - org.pipewire.Helvum
    - org.darktable.Darktable
    - io.github.mhogomchungu.media-downloader
    - io.github.ltiber.Pwall
    - io.dbeaver.DBeaverCommunity
    - com.discordapp.Discord
  tags: ["flatpaks"]
