---
# tasks file for b08x.devworkstation.desktop

- name: Display the value of desktop_my_variable
  ansible.builtin.debug:
    msg: "The value of desktop_my_variable is {{ desktop_my_variable }}"

- name: Ensure Flathub remote repository is present
  community.general.flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org
    method: system
    state: present
  tags: ["flathub"]

- name: Include VS Code installation tasks
  ansible.builtin.include_tasks: vscode.yml

- name: Install Flatpak applications
  community.general.flatpak:
    name: "{{ item }}"
    state: present
    method: system
    remote: flathub
  loop:
    - com.google.Chrome
    - io.github.vikdevelop.SaveDesktop
    - com.mattjakeman.ExtensionManager
    - com.ranfdev.DistroShelf
    - io.github.input_leap.input-leap
    - io.podman_desktop.PodmanDesktop
    - page.tesk.Refine
    - org.gnome.DejaDup
  tags: ["flatpaks"]
