---
desktop_packages:
  gnome:
    - "@gnome-desktop"
    - "@graphical-server-environment"
    - gdm
    - gnome-tweaks
  theme:
    - gtk3-devel
    - gnome-tweaks
    - sassc
    - meson
    - ninja-build
