---
desktop_packages:
  gnome:
    - "@gnome-desktop"
    - "@graphical-server-environment"
    - gdm
    - gnome-tweaks
  theme:
    - gtk3-devel
    - gnome-tweaks
    - sassc
    - meson
    - ninja-build
  qt:
    - qt6-qtbase
    - qt6-qttools
    - qt6-qtmultimedia
    - qt6-qtdeclarative
    - qt5-qtbase
    - qt5-qttools
    - qt5-qtquickcontrols2
    - qt5-qtgraphicaleffects
    - qscintilla-qt5
    - qt5ct
    - qt6ct
  gtk:
    - gtk4
    - gtk3-devel
    - gtksourceview4
    - gtksourceview5
