---
desktop_packages:
  theme:
    - gnome-shell-theme-yaru
    - yaru-gtk2-theme
    - yaru-gtk3-theme
    - yaru-gtk4-theme
    - yaru-gtksourceview-theme
    - yaru-icon-theme
    - yaru-sound-theme
    - yaru-theme
