---
# defaults file for b08x.devworkstation.base

# Variable that will be displayed in debug output
# This demonstrates proper role variable naming with the 'run_' prefix
base_my_variable: "default_value"
base_install_cargo: false

base_go_version: 1.27.1

base_uv_python_version: 3.13
