---
- name: Check if iptables command is available
  ansible.builtin.command: which iptables
  register: iptables_check
  changed_when: false
  ignore_errors: true

- name: Check if DOCKER-USER chain exists
  ansible.builtin.command: iptables -L DOCKER-USER -n
  register: docker_user_chain
  changed_when: false
  ignore_errors: true
  when: iptables_check.rc == 0
  become: true

- name: Ensure libvirt inbound traffic is accepted in DOCKER-USER chain
  ansible.builtin.iptables:
    chain: DOCKER-USER
    in_interface: virbr+
    jump: ACCEPT
    action: insert
    rule_num: 1
    state: present
  when:
    - iptables_check.rc == 0
    - docker_user_chain.rc == 0
  become: true

- name: Ensure libvirt outbound traffic is accepted in DOCKER-USER chain
  ansible.builtin.iptables:
    chain: DOCKER-USER
    out_interface: virbr+
    jump: ACCEPT
    action: insert
    rule_num: 1
    state: present
  when:
    - iptables_check.rc == 0
    - docker_user_chain.rc == 0
  become: true
