---
# tasks file for b08x.devworkstation.coding_agents

- name: Include Antigravity install tasks
  ansible.builtin.include_tasks: antigravity_install.yml
  when: coding_agents_antigravity_state == 'present'

- name: Include Antigravity uninstall tasks
  ansible.builtin.include_tasks: antigravity_uninstall.yml
  when: coding_agents_antigravity_state == 'absent'

- name: Include Antigravity update tasks
  ansible.builtin.include_tasks: antigravity_update.yml
  when: coding_agents_antigravity_state == 'latest'

- name: Include Claude install tasks
  ansible.builtin.include_tasks: claude_install.yml
  when: coding_agents_claude_state == 'present'

- name: Include OpenAI install tasks
  ansible.builtin.include_tasks: openai_install.yml
  when: coding_agents_openai_state == 'present'
