---
base_packages:
  - aria2
  - bat
  - bsdtar
  - caca-utils
  - fd-find
  - ffmpeg
  - ffmpegthumbnailer
  - golang
  - highlight
  - jq
  - kernel-devel
  - kernel-headers
  - kernel-modules
  - kernel-modules-core
  - kernel-modules-extra
  - kernel-modules-extra-matched
  - kernel-tools
  - kernel-tools-libs
  - kitty
  - lm_sensors
  - lm_sensors-devel
  - lsb_release
  - mediainfo
  - mpv
  - nodejs
  - perl-FindBin
  - perl-IPC-Cmd
  - perl-Time-Piece
  - python3-nbconvert
  - sqlite
  - zram-generator
  - zram-generator-defaults
