---
base_packages:
  - aria2
  - bat
  - bsdtar
  - caca-utils
  - fd-find
  - ffmpeg
  - ffmpegthumbnailer
  - flatpak
  - gettext
  - gmp-devel
  # - golang
  - gtksourceview4
  - highlight
  - htop
  - jq
  - kernel-devel
  - kernel-headers
  - kernel-modules
  - kernel-modules-core
  - kernel-modules-extra
  - kernel-modules-extra-matched
  - kernel-tools
  - kernel-tools-libs
  - kitty
  - libffi-devel
  - libyaml-devel
  - lm_sensors
  - lm_sensors-devel
  - lnav
  - lsb_release
  - mediainfo
  - meson
  - micro
  - mpv
  - ninja-build
  - nodejs
  - openssh-server
  - openssl-devel
  - perl-FindBin
  - perl-IPC-Cmd
  - perl-Time-Piece
  - pipx
  - python-unversioned-command
  - python3-devel
  - python3-gobject-devel
  - python3-nbconvert
  - python3-pip
  - rbenv
  - readline-devel
  - ruby-build
  - sqlite
  - uv
  - zlib-devel
  - zram-generator
  - zram-generator-defaults
  - zsh
