---
- name: Install rtirq defaults
  ansible.builtin.copy:
    src: etc/rtirq.conf
    dest: /etc/rtirq.conf
    owner: root
    group: root
    mode: "0644"
  register: tuning_rtirq_config
  when: tuning_rtirq_enabled

- name: Install rtkit.conf
  ansible.builtin.copy:
    src: etc/rtkit.conf
    dest: /etc/rtkit.conf
    owner: root
    group: root
    mode: "0644"
  register: tuning_rtkit_conf
  when: tuning_rtkit_enabled

- name: Install rtkit systemd file
  ansible.builtin.template:
    src: usr/lib/systemd/system/rtkit-daemon.service.j2
    dest: /usr/lib/systemd/system/rtkit-daemon.service
    mode: "0644"
  register: tuning_rtkit_systemd
  notify: Reload systemd
  when: tuning_rtkit_enabled
