---

# clone git flow-avh repository
- name: Clone gitflow-avh repository
  ansible.builtin.git:
    repo: https://github.com/b08x/gitflow-avh.git
    dest: /tmp/gitflow-avh
    clone: true
    update: true
    version: develop
  become: false
  tags: ["gitflow", "base"]

- name: Install git flow-avh
  ansible.builtin.command:
    cmd: make install
    chdir: /tmp/gitflow-avh
    creates: /usr/local/bin/git-flow
  tags: ["gitflow", "base"]
