---
# tasks file for b08x.devworkstation.base

- name: Display the value of base_my_variable
  ansible.builtin.debug:
    msg: "The value of base_my_variable is {{ base_my_variable }}"

- name: Include distribution package variables
  ansible.builtin.include_vars: "{{ ansible_distribution }}.yml"
  tags: ["packages", "distro"]

# ----------------------------------------------------------------------------
# DNF Performance Optimization
# ----------------------------------------------------------------------------

- name: Include DNF configuration tasks
  ansible.builtin.include_tasks: dnf.yml
  tags: ["dnf", "base", "repos"]

# ----------------------------------------------------------------------------
# Repository Configuration
# ----------------------------------------------------------------------------

- name: Include Distribution Specific Repository Tasks
  ansible.builtin.include_tasks: "distro/{{ ansible_distribution }}.yml"
  when:
    - enable_third_party_repos | default(true)
  tags: ["repos", "base"]

- name: Install Base packages
  tags: ["packages", "base"]
  block:
    - name: Install Base packages
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
        allowerasing: true
      with_items:
        - "{{ base_packages }}"

  rescue:
    - name: Handle package installation failures
      ansible.builtin.debug:
        msg: "Failed to install some Base packages. Please check the error message above."

- name: Configure zram-generator
  ansible.builtin.copy:
    content: |
      [zram0]
      zram-size = min(ram, 8192)
      compression-algorithm = zstd
      swap-priority = 100
    dest: /etc/systemd/zram-generator.conf
    mode: "0644"
  notify: Reload zram

- name: Include gitflow installation tasks
  ansible.builtin.include_tasks: gitflow.yml
  tags: ["gitflow", "base"]

- name: Include cargo installation tasks
  ansible.builtin.include_tasks: cargo.yml
  tags: ["cargo", "base"]

- name: Include Intel installation tasks
  ansible.builtin.include_tasks: intel.yml
  tags: ["intel", "base"]

- name: Include fzf installation tasks
  ansible.builtin.include_tasks: fzf.yml
  tags: ["fzf", "base"]

- name: Include inxi installation tasks
  ansible.builtin.include_tasks: inxi.yml
  tags: ["inxi", "base"]

- name: Include Ranger installation tasks
  ansible.builtin.include_tasks: ranger.yml
  tags: ["ranger", "base"]

- name: Include Zsh installation tasks
  ansible.builtin.include_tasks: zsh.yml
  tags: ["zsh", "base"]
